config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :reviews
  root to: 'reviews#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booze_review_details.rb
# frozen_string_literal: true

class BoozeReviewDetails < ApplicationRecord
  include ReviewDetails

  def self.type
    'Booze'
  end
end

app/models/concerns/review_details.rb
# frozen_string_literal: true

module ReviewDetails
  extend ActiveSupport::Concern

  def parent_review
    Review.find_by(review_details_id: id)
  end

  included do
    has_one :review, as: :review_details, dependent: :destroy
  end
end

app/models/movie_review_details.rb
# frozen_string_literal: true

class MovieReviewDetails < ApplicationRecord
  include ReviewDetails

  def self.type
    'Movie'
  end
end

app/models/restaurant_item_review_details.rb
# frozen_string_literal: true

class RestaurantItemReviewDetails < ApplicationRecord
  include ReviewDetails

  belongs_to :restaurant_review_details

  def self.type
    'Restaurant Item'
  end
end

app/models/restaurant_review_details.rb
# frozen_string_literal: true

class RestaurantReviewDetails < ApplicationRecord
  include ReviewDetails

  has_many :restaurant_item_review_details, class_name: 'RestaurantItemReviewDetails', dependent: :destroy

  def self.type
    'Restaurant'
  end
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  TYPES = [
    BoozeReviewDetails,
    RestaurantItemReviewDetails,
    RestaurantReviewDetails,
    MovieReviewDetails,
    TvShowReviewDetails,
    TvShowSeasonReviewDetails,
    VideoGameReviewDetails
  ].freeze

  belongs_to :review_details, polymorphic: true, dependent: :destroy

  def type
    review_details.class.type
  end

  def self.detail_class_for_type(type)
    TYPES.find { |type_class| type_class.type == type }
  end
end

app/models/tv_show_review_details.rb
# frozen_string_literal: true

class TvShowReviewDetails < ApplicationRecord
  include ReviewDetails

  has_many :tv_show_season_review_details, class_name: 'TvShowSeasonReviewDetails', dependent: :destroy

  def self.type
    'TV Show'
  end
end

app/models/tv_show_season_review_details.rb
# frozen_string_literal: true

class TvShowSeasonReviewDetails < ApplicationRecord
  include ReviewDetails

  belongs_to :tv_show_review_details

  def self.type
    'TV Show Season'
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    user ||= User.create!(name: data['name'],
                          email: data['email'],
                          password: Devise.friendly_token[0, 20])

    user
  end
end

app/models/video_game_review_details.rb
# frozen_string_literal: true

class VideoGameReviewDetails < ApplicationRecord
  include ReviewDetails

  def self.type
    'Video Game'
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  def index
    @reviews = Review.all.order(created_at: :desc)
  end

  def new
    if current_user.present? && current_user.admin?
      @type = params[:type]
      details = Review.detail_class_for_type(params[:type]).new
      @review = Review.new(review_details: details)
    else
      redirect_to reviews_path
    end
  end

  def show
    if current_user.present? && current_user.admin?
      @id = params[:id]
      @review = Review.find(@id)
    else
      redirect_to reviews_path
    end
  end

  def create
    ReviewService.create_review(params) if current_user.present? && current_user.admin?

    redirect_to reviews_path
  end

  def update
    ReviewService.update_review(params) if current_user.present? && current_user.admin?

    redirect_to reviews_path
  end

  def destroy
    Review.find(params[:id]).destroy if current_user.present? && current_user.admin?

    redirect_to reviews_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except('extra')
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/reviews_helper.rb
# frozen_string_literal: true

module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Max Reviews Everything</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/_review_form.html.erb
<div class="row">
  Name
  <%= f.text_field(:name) %>
</div>
<div class="row">
  Rating
  <%= f.number_field(:rating, min: 0, max: 5.5, step: 0.5) %>
</div>
<div class="row">
  Body
  <%= f.text_area(:body, size: "24x6") %>
</div>
<div class="row">
  Url
  <%= f.text_field(:url) %>
</div>
<%= hidden_field_tag(:type, @review.type) %>

<% case @review.review_details %>
  <% when BoozeReviewDetails %>
    <%= render partial: '/reviews/review_forms/booze', locals: {f: f} %>
  <% when RestaurantReviewDetails %>
    <%= render partial: '/reviews/review_forms/restaurant', locals: {f: f} %>
  <% when RestaurantItemReviewDetails %>
    <%= render partial: '/reviews/review_forms/restaurant_item', locals: {f: f} %>
  <% when VideoGameReviewDetails %>
    <%= render partial: '/reviews/review_forms/video_game', locals: {f: f} %>
  <% when MovieReviewDetails %>
    <%= render partial: '/reviews/review_forms/movie', locals: {f: f} %>
  <% when TvShowReviewDetails %>
    <%= render partial: '/reviews/review_forms/tv_show', locals: {f: f} %>
  <% when TvShowSeasonReviewDetails %>
    <%= render partial: '/reviews/review_forms/tv_show_season', locals: {f: f} %>
<% end %>

app/views/reviews/index.html.erb
<div class="login">
  <% if user_signed_in? %>
    <p>
      Logged in as 
      <span style="color: <%= current_user.admin ? 'blue' : 'black' %>"><%= current_user.email %></span>
    </p>

    <% if current_user.admin %>
      <p>
        <%= form_tag new_review_path, method: :get do %>
          Add a review: 

          <%= select_tag :type, options_for_select(Review::TYPES.map(&:type)), include_blank: true, :onchange => "this.form.submit()" %>
        <% end %>
      </p>
    <% else %>
     <p>&lt;USER TRACKING ENGAGED&gt;</p>
    <% end %>
  <% else %>
    <%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path %>
  <% end %>
</div>

<div class="container">
  <% @reviews.each do |review| %>
    <% if current_user&.admin %>
      <div class="show">
        <a href="<%= review_path(review.id) %>">🗿</a>
      </div>
    <% end %>
    <% case review.review_details %>
    <% when RestaurantItemReviewDetails %>
      <%= render partial: '/reviews/review_types/restaurant_item', locals: {review: review} %>
    <% when RestaurantReviewDetails %>
      <%= render partial: '/reviews/review_types/restaurant', locals: {review: review} %>
    <% when BoozeReviewDetails %>
      <%= render partial: '/reviews/review_types/booze', locals: {review: review} %>
    <% when VideoGameReviewDetails %>
      <%= render partial: '/reviews/review_types/video_game', locals: {review: review} %>
    <% when TvShowReviewDetails %>
      <%= render partial: '/reviews/review_types/tv_show', locals: {review: review} %>
    <% when TvShowSeasonReviewDetails %>
      <%= render partial: '/reviews/review_types/tv_show_season', locals: {review: review} %>
    <% when MovieReviewDetails %>
      <%= render partial: '/reviews/review_types/movie', locals: {review: review} %>
    <% else %>
    <div class="container review">
      <div class="row">
        <div class="col-sm name">
          <%= review.name %>
        </div>
        <div class="col-sm rating">
          <%= review.rating %> / 5.5
        </div>
        <div class="col-sm type">
          <%= review.review_details.type %>
        </div>
      </div>
      <div class="row review-body">
        <div class="col">
          <%= review.body %>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1>Create a Review</h1>

  <%= form_with(model: @review) do |f| %>
    <%= render partial: '/reviews/review_form', locals: {f: f} %>

    <div class="row">
      <%= f.submit('Create') %>
    </div>
  <% end %>
</div>

app/views/reviews/review_forms/_booze.html.erb
<%= f.fields_for :review_details, @review.review_details do |details_form| %>
  <div class="row">
    Subtype
    <%= details_form.text_field(:subtype) %>
  </div>

  <div class="row">
    Maker
    <%= details_form.text_field(:maker) %>
</div>
<% end %>

app/views/reviews/review_forms/_movie.html.erb
<%= f.fields_for :review_details, @review.review_details do |details_form| %>
  <div class="row">
    Director
    <%= details_form.text_field(:director) %>
  </div>

  <div class="row">
    Actors
    <%= details_form.text_field(:actors) %>
  </div>

  <div class="row">
    Genre
    <%= details_form.text_field(:genre) %>
  </div>
<% end %>

app/views/reviews/review_forms/_restaurant.html.erb
<%= f.fields_for :review_details, @review.review_details do |details_form| %>
  <div class="row">
    Subtype
    <%= details_form.text_field(:subtype) %>
  </div>

  <div class="row">
    Location
    <%= details_form.text_field(:location) %>
  </div>
<% end %>

app/views/reviews/review_forms/_restaurant_item.html.erb
<%= f.fields_for :review_details, @review.review_details do |details_form| %>
  <div class="row">
    Subtype
    <%= details_form.text_field :subtype %>
  </div>

  <div class="row">
    Restaurant
    <%= details_form.select :restaurant_review_details_id, options_for_select(RestaurantReviewDetails.all.map { |restaurant| [restaurant.parent_review.name, restaurant.id] }, details_form.object.restaurant_review_details_id) %>
  </div>
<% end %>

app/views/reviews/review_forms/_tv_show.html.erb
<%= f.fields_for :review_details, @review.review_details do |details_form| %>
  <div class="row">
    Network
    <%= details_form.text_field(:network) %>
  </div>

  <div class="row">
    Actors
    <%= details_form.text_field(:actors) %>
  </div>

  <div class="row">
    Genre
    <%= details_form.text_field(:genre) %>
  </div>
<% end %>

app/views/reviews/review_forms/_tv_show_season.html.erb
<%= f.fields_for :review_details, @review.review_details do |details_form| %>
  <div class="row">
    TV Show
    <%= details_form.select :tv_show_review_details_id, options_for_select(TvShowReviewDetails.all.map { |tv_show| [tv_show.parent_review.name, tv_show.id] }, details_form.object.tv_show_review_details_id) %>
  </div>
<% end %>

app/views/reviews/review_forms/_video_game.html.erb
<%= f.fields_for :review_details, @review.review_details do |details_form| %>
  <div class="row">
    Genre
    <%= details_form.text_field(:genre) %>
  </div>

  <div class="row">
    Developer
    <%= details_form.text_field(:developer) %>
  </div>
<% end %>

app/views/reviews/review_types/_booze.html.erb
<div class="container review booze">
  <div class="row">
    <div class="col-sm name left">
      <%= review.name %>
    </div>
    <div class="col-sm">
      <%= review.review_details.maker %>
    </div>
    <div class="col-sm rating">
      <%= review.rating %> / 5.5
    </div>
    <div class="col-sm type">
      <%= review.review_details.subtype %>
    </div>
  </div>
  <div class="row review-body">
    <div class="col">
      <%= review.body %>
    </div>
  </div>
</div>

app/views/reviews/review_types/_movie.html.erb
<div class="container review movie">
  <div class="row">
    <div class="col-sm name left">
      <%= review.name %>
    </div>
    <div class="col-sm">
      <p><%= review.review_details.director %></p>
      <p><%= review.review_details.actors.join(', ') %></p>
    </div>
    <div class="col-sm rating">
      <%= review.rating %> / 5.5
    </div>
    <div class="col-sm type">
      <%= review.review_details.genre %>
    </div>
  </div>
  <div class="row review-body">
    <div class="col">
      <%= review.body %>
    </div>
  </div>
</div>

app/views/reviews/review_types/_restaurant.html.erb
<div class="container review restaurant">
  <div class="row">
    <div class="col-sm name left">
      <%= review.name %>
    </div>
    <div class="col-sm">
      <%= review.review_details.location %>
    </div>
    <div class="col-sm rating">
      <%= review.rating %> / 5.5
    </div>
    <div class="col-sm type">
      <%= review.review_details.subtype %>
    </div>
  </div>
  <div class="row review-body">
    <div class="col">
      <%= review.body %>
    </div>
  </div>
</div>

app/views/reviews/review_types/_restaurant_item.html.erb
<div class="container review restaurant-item">
  <div class="row">
    <div class="col-sm left">
      <span class="name"><%= review.name %></span>

      from

      <span class="name"><%= review.review_details.restaurant_review_details.parent_review.name %></span>
    </div>
    <div class="col-sm rating">
      <%= review.rating %> / 5.5
    </div>
    <div class="col-sm type">
      <%= review.review_details.subtype %>
    </div>
  </div>
  <div class="row review-body">
    <div class="col">
      <%= review.body %>
    </div>
  </div>
</div>

app/views/reviews/review_types/_tv_show.html.erb
<div class="container review tv-show">
  <div class="row">
    <div class="col-sm name left">
      <%= review.name %>
    </div>
    <div class="col-sm">
      <p><%= review.review_details.network %></p>
      <p><%= review.review_details.actors.join(', ') %>
    </div>
    <div class="col-sm rating">
      <%= review.rating %> / 5.5
    </div>
    <div class="col-sm type">
      <%= review.review_details.genre %>
    </div>
  </div>
  <div class="row review-body">
    <div class="col">
      <%= review.body %>
    </div>
  </div>
</div>

app/views/reviews/review_types/_tv_show_season.html.erb
<div class="container review tv-show-season">
  <div class="row">
    <div class="col-sm name left">
      <%= review.name %>      
      
      of

      <span class="name"><%= review.review_details.tv_show_review_details.parent_review.name %></span>
    </div>
    <div class="col-sm rating">
      <%= review.rating %> / 5.5
    </div>
  </div>
  <div class="row review-body">
    <div class="col">
      <%= review.body %>
    </div>
  </div>
</div>

app/views/reviews/review_types/_video_game.html.erb
<div class="container review video-game">
  <div class="row">
    <div class="col-sm name left">
      <%= review.name %>
    </div>
    <div class="col-sm">
      <%= review.review_details.developer %>
    </div>
    <div class="col-sm rating">
      <%= review.rating %> / 5.5
    </div>
    <div class="col-sm type">
      <%= review.review_details.genre %>
    </div>
  </div>
  <div class="row review-body">
    <div class="col">
      <%= review.body %>
    </div>
  </div>
</div>

app/views/reviews/show.html.erb
<div class="container">
  <%= form_with(model: @review, method: :put) do |f| %>
    <%= render partial: '/reviews/review_form', locals: {f: f} %>

    <div class="row">
      <%= f.submit('Update') %>
    </div>
  <% end %>
  <div class="row">
    <%= button_to 'Delete', review_path(@review.id), method: :delete %>
  </div>
</div>